Repository next-step/blog, pull requests merged in 2020-12, with the labels that each got.

#58 [2기 조윤호][1주차]Node.js 표준 입력 받기(readline)
  2기(2020.11)/YUJO42/Node.js-readline.md
Labels: TeamE

#52 [2기 김홍빈][1주차] 11월 3주차 스프링시큐리티와 인증
  2기(2020.11)/allen/step01.md
Labels: TeamB

#64 1주차 우리는 인프라 환경을 어떻게 구축해야 하는가? - AWS 상담편
  .gitignore
  2기(2020.11)/oen142/step1.md
  2기(2020.11)/oen142/step2.md
Labels: TeamG

#51 [2기 HansolLee][1주차] 11월 3주차 주간회고록
  .gitignore
  1기(2020.10)/sunivers/step02.md
  2기(2020.11)/step1.md
  2기(2020.11)/step2.md
Labels: TeamB

#70 [2기 2SOOY][2주차] 조바심과 마주하기
  2기(2020.11)/2SOOY/step1.md
Labels: TeamB

#69 [2기 makerjun][2주차] 파병일기의 시작
  2기(2020.11)/makerjun/journey.md
  2기(2020.11)/makerjun/voice-of-past.md
Labels: TeamB

#50 [2기 나무][1주차] 주간 회고
  2기(2020.11)/나무/2기.md
Labels: TeamB

#54 [2기 devhyun] 1주차 : 리드미 작성에 대한 짧은 고찰
  2기(2020.11)/devhyun/step1.md
Labels: TeamC

#55 [2기 JamieShin] 1주차 : 퇴사 그리고 새로운 시작
  2기(2020.11)/JamieShin/step1.md
Labels: TeamC

#60 [2기 younho9][1주차] 2020년 회고
  2기(2020.11)/step.md
  2기(2020.11)/younho9/step1.md
  2기(2020.11)/younho9/step2.md
Labels: TeamF

#62 [2기 그니][1주 차] 슬랙 로깅 적용하기
  2기(2020.11)/그니/slack-logging.md
Labels: TeamG

#63 [2기 dwlee][2주차] 신입 개발자 생존의 기술이라는 책을 읽고나서 정리한 글
  2기(2020.11)/dwlee/2주차/second.md
Labels: TeamG

#65 [2기 그니][2주 차] WebSocket 기술에 대하여
  2기(2020.11)/makerjun/websocket.md
Labels: TeamA

#78 [2기 김종완Wani] Gradle 기본 Task 정리 외 1건
  .gitignore
  2기(2020.11)/oen142/step3.md
Labels: TeamD

#74 [2기 김세윤][2주차] MVC 패턴이란?
  2기(2020.11)/rutgo/step2.md
Labels: TeamC

#87 [2기 JunilHwang][3주차] 2021 새해 계획
  2기(2020.11)/JunilHwang/step2.md
Labels: TeamF

#72 [2기 정회형][2주차] JWT에 관한 5가지 사실
  2기(2020.11)/hotheadfactory/step2.md
  2기(2020.11)/hotheadfactory/step3.md
Labels: TeamB

#76 [2기 Sky][2주차] 2020년도 회고록
  2기(2020.11)/Sky/step02.md
Labels: TeamD

#71 [2기 toneyparky][2주차] 12월을 어찌 보낼까
  2기(2020.11)/toneyparky/step2.md
Labels: TeamB
