Repository next-step/blog, pull requests merged in 2020-10, with the labels that each got.

#2 [1기 oen142] blackcoffee스터디, 개발자 세금상식
  .gitignore
Labels: TeamA

#7 [1기 eyabc] 자바스크립트 airbnb 스타일 가이드
  1기(2020.10)/eyabc/step01.md
Labels: TeamB

#8 [1기 전환오] 10월 - C작업, 개선하기
  1기(2020.10)/jho2301/step01.md
Labels: TeamC

#6 [1기 HansolLee]1주차 글쓰기(2020년 10월 2주차 회고록)
  1기(2020.10)/HansolLee/step1.md
Labels: TeamB

#4 [1기 JunilHwang] 2020년 9월 회고
  1기(2020.10)/JunilHwang/step1.md
Labels: TeamA

#10 [1기 장현석] 우아한 테크러닝 3기 React & TypeScript 후기
  1기(2020.10)/devJang/step-1.md
Labels: TeamC

#9 [1기 김경록] 2020년 늦은 상반기 회고록
  1기(2020.10)/rok93/step1.md
Labels: TeamC

#1 [1기 lsw1164] 브라우저는 어떻게 동작할까?
  1기(2020.10)/lsw1164/step.md
Labels: TeamA

#13 [1기 메이커준] 프롤로그
  1기(2020.10)/makerjun/prologue.md
Labels: TeamD

#5 [1기 나무] 주간 회고
  1기(2020.10)/나무/step.md
Labels: TeamB

#11 [1기 홍현의] 2020 하반기 코딩 테스트 회고
  1기(2020.10)/hongjehong/step.md
Labels: TeamD

#12 [1기 박소영] try...catch 그리고 에러 핸들링
  1기(2020.10)/sunivers/step01.md
  1기(2020.10)/sunivers/step02.md
Labels: TeamD

#17 [1기 박은영] 내 글 써보기
  1기(2020.10)/eyabc/step02.md
Labels: TeamE

#20 [1기 JunilHwang] [2주차] Vanilla Javascript로 웹 컴포넌트 만들기
  1기(2020.10)/JunilHwang/step2.md
Labels: TeamA
