Repository next-step/blog, pull requests merged in 2020-11, with the labels that each got.

#21 [1기 박소영] 10월 4주차 주간 회고
  1기(2020.10)/sunivers/step02.md
Labels: TeamB

#15 [1기 가너도루] "개발자가 적성에 맞는지? feat. 7년차 개발자"를 읽고
  1기(2020.10)/ganeodolu/step1.md
Labels: TeamE

#27 [1기 나무][3주차] 호이스팅
  1기(2020.10)/나무/step.md
Labels: TeamD

#23 [1기 조윤호][2주차]비전공자가 컴공💻 과목들을 공부하고 느낀 점(feat. 독학사 4단계 컴퓨터과학 시험 후기)
  1기(2020.10)/YUJO42/첫번째 글.md
Labels: TeamB

#28 [1기 JunilHwang][3주차] 유년시절 이야기
  1기(2020.10)/JunilHwang/step3.md
  1기(2020.10)/JunilHwang/step4.md
Labels: TeamD

#30 [1기 Sky][3주차] 10월 회고록
  1기(2020.10)/Sky/octoberDiary.md
Labels: TeamE

#35 [1기 메이커준][4주차] 5. '좋아하는 시나 소설, 노래 중심으로' 자신을 자유롭게 소개해 주세요.
  .gitignore
  1기(2020.10)/makerjun/my-story.md
Labels: TeamF

#19 [1기 lsw1164] 새로운 것을 배우려면?
  1기(2020.10)/lsw1164/README.md
Labels: TeamA

#31 [1기 박소영][3주차] 클린코드 스터디 후기
  1기(2020.10)/sunivers/step03.md
Labels: TeamE

#32 [1기 가너도루][3주차] 내 문장이 그렇게 이상한가요? 를 읽으면서
  1기(2020.10)/ganeodolu/step2.md
Labels: TeamE

#34 [1기 조윤호][4주차][JS]for 반복문
  1기(2020.10)/YUJO42/step1.md
  1기(2020.10)/YUJO42/step2.md
Labels: TeamF

#49 [2기 eyabc][1주차] 최근에 적었던 주간회고 목표 피드백
  2기(2020.11)/eyabc/step01.md
Labels: TeamA

#56 [2기 JunilHwang][1주차] 유년시절 이야기 Part 03
  2기(2020.11)/JunilHwang/step1.md
Labels: TeamE

#45 [2기 dongwooklee96][1주차] 개발자가 갖춰야할 9가지 기술
  1기(2020.10)/dongwook/ch1/blog.md
Labels: TeamA

#47 [2기 hotheadfactory][1주차] 우아한테크코스 - 끝나지 않은 모험
  2기(2020.11)/hotheadfactory/step1.md
Labels: TeamA

#53 [2기 김세윤][1주차] [if(kakao)2020] JUnit5를 시작하며
  2기(2020.11)/rutgo/step1.md
Labels: TeamC

#59 [2기 toneyparky] 1주차 : 글을 왜 안 쓰는가
  2기(2020.11)/toneyparky/step1.md
Labels: TeamF
