Repository next-step/blog, pull requests merged in 2021-02, with the labels that each got.

#114 [3기 makerjun][1주차] 만월의 밤 함상에서의 만찬
  3기(2021.01)/makerjun/feast.md
Labels: TeamE

#101 [3기 read][1주차] DOM 요소의 swap
  3기(2021.01)/read/first_week.md
Labels: TeamA

#103 [3기 김홍빈][1주차] 신입 백엔드개발자 한달 생활기
  3기(2021.01)/allen/step1.md
Labels: TeamA

#104 [3기 박현철][1주차] 21년 상반기 목표
  .DS_Store
  3기(2021.01)/.DS_Store
  3기(2021.01)/macbook_dev/.DS_Store
  3기(2021.01)/macbook_dev/step1.md
  3기(2021.01)/macbook_dev/step2.md
Labels: TeamB

#105 [3기 abcdsds][1주차] 쿠버네티스 컴포넌트 구조
  3기(2021.01)/abcdsds/step1.md
Labels: TeamB

#108 [3기 pje1740][1주차] You Don't Know JS Yet - Scope & Closures 요약 및 감상 (2)클로저
  3기(2021.01)/pje1740/step1.md
Labels: TeamC

#109 [3기 6mn12j][1주차] 코어자바스크립트 2장 실행컨텍스트
  3기(2021.01)/6mn12j/[3기 6mn12j][1주차] 코어자바스크립트 2장 실행컨텍스트
Labels: TeamC

#111 [3기 w-beom][1주차] 모던 자바 인 액션 챕터1 정리
  3기(2021.01)/w-beom/step1.md
Labels: TeamD

#113 [3기 HansolLee][1주차] 2021년 1월 4주차 회고록
  3기(2021.01)/HansolLee/step01.md
Labels: TeamE

#117 [3기 전환오][1주차] 영국 정부의 디지털 서비스 설계 원칙
  3기(2021.01)/jho2301/step1.md
Labels: TeamF

#118 [3기 hankkuu][1주차] 다시 시작한다는 용기
  3기(2021.01)/hankkuu/step1.md
Labels: TeamF

#120 [3기 조윤호][2주차] [IT-article-archive]#6 글 쓰기 화면 UI 및 기능 만들기(feat. 오류 수정)
  3기(2021.01)/YUJO42/2주차.md
Labels: TeamA

#125 [3기 povia][2주차] 2020년 회고와 새로운 변화들
  3기(2021.01)/povia/step1.md
  3기(2021.01)/povia/step2.md
Labels: TeamC

#121 [3기 박현철][2주차]개발자의 글쓰기 리뷰 / (추가됨) 객체지향의 사실과 오해 리뷰 / (추가됨) 2월 학습 목표
  3기(2021.01)/macbook_dev/step2.md
Labels: TeamA

#123 [3기 Jun][2주차] Debounce And Throttle
  3기(2021.01)/Jun/throttle_debounce.md
Labels: TeamB

#124 [3기 오태경][2주차] 책 데이터베이스 첫 걸음 3장, 4장 포스팅
  3기(2021.01)/ohtaeg/step2.md
Labels: TeamB

#127 [3기 TheWing][2주차] 블랙커피 스터디 2주차 학습 방법에 대한 고민
  3기(2021.01)/TheWing/step2.md
Labels: TeamC

#128 [3기 makerjun][2주차] [건축] 5. 사막위에서 지어지는 꿈
  3기(2021.01)/makerjun/building.md
  3기(2021.01)/makerjun/feast.md
Labels: TeamD

#129 [3기 OhGun][3주차]깃허브 PR에 대해 알게 되었습니다
  3기(2021.01)/OhGun/step01.md
Labels: TeamA

#130 [3기 강한규][2주차] Good Commit Message란 무엇인가?
  3기(2021.01)/hankkuu/step2.md
Labels: TeamA

#132 [3기 abcdsds][3주차] 나만의 쿠버네티스 injector 만들기
  .gitignore
  3기(2021.01)/abcdsds/step3.md
Labels: TeamA

#136 [김종완]구직 이메일 구독 서비스 프로젝트 시작
  1기(2020.10)/oen142/step1.md
  1기(2020.10)/oen142/step3.md
  3기(2021.01)/oen142/step1.md
Labels: TeamC

#139 [3기 TheWing][3주차] 블랙커피 스터디 , LiveStudy(Enum, Annotation)
  3기(2021.01)/TheWing/step3.md
Labels: TeamD

#143 4주차 부자 계획 세워봤습니다
  3기(2021.01)/dali/02.week.md
  3기(2021.01)/dali/03.week.md
  3기(2021.01)/dali/04.week.md
Labels: TeamA

#145 [3기 박현철][4주차]테스트 코드 첫걸음
  3기(2021.01)/macbook_dev/step2.md
  3기(2021.01)/macbook_dev/step3.md
  3기(2021.01)/macbook_dev/step4.md
Labels: TeamB

#147 [3기 강한규] [4주차] Interface와 Application 제작
  3기(2021.01)/hankkuu/step3.md
  3기(2021.01)/hankkuu/step4.md
Labels: TeamC
